# Generated by Django 5.2.1 on 2025-06-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_alter_product_review_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
