# Generated by Django 5.2.1 on 2025-06-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_remove_product_review_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created',
            new_name='created_date',
        ),
    ]
